### ISSUE TITLE
Running this on bamboo and Locally get the same error 

### ISSUE THREAD

**Issue by dmodoomsirius** [DarkGuardsman/MavenPageMaker#3]
Exception in thread "main" java.lang.NullPointerException
        at java.lang.String.replace(String.java:2180)
        at com.builtbroken.maven.page.Version.toHtml(Version.java:83)
        at com.builtbroken.maven.page.Page.outputToFile(Page.java:57)
        at com.builtbroken.maven.page.PageBuilder.makeHtmlFile(PageBuilder.java:120)
        at com.builtbroken.maven.page.PageBuilder.buildHtmlTable(PageBuilder.java:102)
        at com.builtbroken.maven.page.PageBuilder.buildPage(PageBuilder.java:65)
        at com.builtbroken.maven.Main.main(Main.java:145)

Config
# 
# Thu Jan 15 11:30:06 EST 2015

adfly=2380428
maven=ci.builtbroken.com/maven
group=com.builtbroken.voltzengine
output_location=/var/www/html/maven/com/builtbroken/voltzengine/VoltzEngine/
id=VoltzEngine

**Comment by dmodoomsirius** [comment]
Found out issue on irc

**Comment by DarkGuardsman** [comment]
Issue was caused by build # being null in the plugin. This was fixed by fixing the maven-meta and initializing the build number to an empty string. This way if it happens again the plugin will not craft.

**Comment by dmodoomsirius** [comment]
I'll reopen so you have a reminder
